# Generated by Django 4.2.4 on 2023-09-06 22:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=30)),
                ("amount", models.IntegerField()),
                ("num_packets", models.IntegerField()),
                ("packet_size", models.IntegerField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("D", "Trockenfutter"),
                            ("W", "Nassfutter"),
                            ("S", "Snacks"),
                        ],
                        max_length=1,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("g", "Gramm"),
                            ("ml", "Milliliter"),
                            ("stk", "Stück"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "Food",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("birthday_on", models.DateField(blank=True)),
                ("race", models.CharField(max_length=40)),
                ("color", models.CharField(default="#ffffff", max_length=7)),
                ("description", models.TextField(default="")),
                (
                    "picture",
                    models.ImageField(
                        default="images/default.png", upload_to="images/"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "Pet",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                (
                    "fed_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meals",
                        to="api.food",
                    ),
                ),
                ("pets", models.ManyToManyField(to="api.pet")),
            ],
            options={
                "db_table": "Meal",
            },
        ),
    ]
