# Generated by Django 4.2.3 on 2023-08-07 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meal",
            name="pet",
        ),
        migrations.AddField(
            model_name="meal",
            name="pet",
            field=models.ManyToManyField(to="api.pet"),
        ),
    ]
