# Generated by Django 4.2.4 on 2023-09-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="food",
            name="category",
            field=models.CharField(
                choices=[("W", "Nassfutter"), ("D", "Trockenfutter"), ("S", "Snacks")],
                max_length=1,
            ),
        ),
    ]
