# Generated by Django 4.2.4 on 2023-09-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_food_active_alter_food_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="food",
            name="pl",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
