# Generated by Django 4.2.3 on 2023-09-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pet_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='pet',
            new_name='pets',
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('D', 'Trockenfutter'), ('W', 'Nassfutter'), ('S', 'Snacks')], max_length=1),
        ),
        migrations.AlterField(
            model_name='meal',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='api.food'),
        ),
    ]
