# Generated by Django 4.2.3 on 2023-09-24 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='food',
        ),
    ]
