# Generated by Django 4.2.3 on 2023-11-19 15:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_schedule_amount_alter_schedule_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='last_used',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
