# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx
version: '3.8'

services:
  django:
    container_name: django
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${POSTGRES_USER}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      # uncomment the following lines to use postgres instead of sqlite
      # SQL_ENGINE: django.db.backends.postgresql
      # SQL_DATABASE: ${POSTGRES_DB}
      # SQL_USER: ${POSTGRES_USER}
      # SQL_PASSWORD: ${POSTGRES_PASSWORD}
      # SQL_HOST: db
      # SQL_PORT: 5432
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
  
  # uncomment the following lines to use postgres instead of sqlite
  # db:
  #   image: postgres:15-alpine
  #   volumes:
  #     - ./postgres_data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_DB: ${POSTGRES_DB}