# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx
# start a dev server
version: '3.8'

services:
  backend:
    build: ./backend
    command: > 
     sh -c "python manage.py migrate &&
            python manage.py ensureadminuser &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      TUYA_ID: ${TUYA_ID}
      TUYA_IP: ${TUYA_IP}
      TUYA_KEY: ${TUYA_KEY}
    volumes:
      - ./backend:/app
    depends_on:
      - redis

  redis:
    image: redis:alpine

  frontend:
    build:
      context: ./frontend
    ports:
      - 24678:24678
    command: "yarn dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.nuxt

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - ./backend/media:/media
    depends_on:
      - backend
      - frontend