# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx
version: '3.8'

services:
  backend:
    build: ./backend
    command: > 
     sh -c "python manage.py migrate &&
            python manage.py ensureadminuser &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      SQL_ENGINE: ${SQL_ENGINE}
      SQL_DATABASE: ${SQL_DATABASE}
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_HOST: ${SQL_HOST}
      SQL_PORT: ${SQL_PORT}
      TUYA_ID: ${TUYA_ID}
      TUYA_IP: ${TUYA_IP}
      TUYA_KEY: ${TUYA_KEY}
    volumes:
      - ./backend:/app

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=${SQL_DATABASE}
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
    volumes:
      - ./database:/var/lib/postgresql/data/

  frontend: # just to build the page on startup
    build:
      context: ./frontend
    command: "npx nuxi generate"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.nuxt

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/.output:/output
      - ./backend/media:/media
    depends_on:
      - backend