# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx
version: '3.8'

services:
  backend:
    container
    build: .
    command: > 
     sh -c "python manage.py migrate &&
            python manage.py ensureadminuser &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_SECRET_KEY: ${POSTGRES_USER}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - .:/app
    ports: 
      - 8000:8000

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/.output/public:/public
    depends_on:
      - backend