# Generated by Django 4.2.4 on 2023-08-02 10:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("brand", models.CharField(max_length=30)),
                (
                    "category",
                    models.CharField(
                        choices=[("D", "Dry"), ("W", "Wet"), ("S", "Snack")],
                        max_length=1,
                    ),
                ),
                ("price", models.IntegerField()),
                (
                    "unit",
                    models.CharField(choices=[("g", "g"), ("l", "ml")], max_length=1),
                ),
            ],
            options={
                "db_table": "Food",
            },
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.IntegerField()),
                ("race", models.CharField(max_length=40)),
            ],
            options={
                "db_table": "Pet",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    models.DateTimeField(blank=True, default=django.utils.timezone.now),
                ),
                ("quantity", models.IntegerField()),
                (
                    "food",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.food"
                    ),
                ),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.pet"
                    ),
                ),
            ],
            options={
                "db_table": "Meal",
            },
        ),
    ]
