# Generated by Django 4.2.3 on 2023-07-30 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetFeeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
        migrations.AlterModelTable(
            name='meal',
            table='Meal',
        ),
        migrations.AlterModelTable(
            name='pet',
            table='Pet',
        ),
    ]
